fname: ../data/filtered_genotyped_combined_outgroup_208samples_pass_filter5_renamed.vcf
samples: ../data/list_samples.yml
outgroup: C_navitas
N_NA: 46
N_BR: 20
N_EU: 141
MAF: 0.05
models:
    M31: [red, o]
    M3B: [red, ^]
    M32: [green, o]
    M33: [green, ^]
    M34: [blue, o]
    M3C: [blue, ^]
    M35: [green, s]
    M36: [green, v]
    M37: [red, s]
    M38: [red, v]
    M39: [blue, s]
    M3A: [blue, v]
    M3D: [gray, o]
    M40: [gray, s]
    M41: [deepskyblue, o]
    M44: [deepskyblue, s]
windows:
    max_dist: 10000
    max_width: 10000
    min_sites: 5
simul:
    nthreads: 40
    nbatch: 200
    szbatch: 1000
    thin: 100
priors:
    nr: 10000
    nbins: 30
plot:
    maxi: 10000
    nbins: 50
lda:
    maxi: 100000
    thin: 1000
    models: [M31, M3B, M32, M33, M34, M3C, M35, M36,
             M37, M38, M39, M3A, M3D, M40, M41, M44]
    struct: [[[1,2], [3,4], [5,6]],
             [[7,8], [9,10], [11,12]],
             [[13,14], [14,15], 0]]
        # a matrix with rows=rows of the picture
        # columns=columns of the picture
        # item: 2-item list giving the dimensions to use for that plot
        # or 0 for disabling the plot
ranger:
    nthreads: 8
    lim: [100000]
post:
    nbatch: 100
    szbatch: 100
    thin: 10
    nthreads: 40
    nbins: 100
