fname: ../../data/filtered_genotyped_combined_outgroup_208samples_pass_filter5_renamed.vcf
samples: ../../data/list_samples.yml
outgroup: C_navitas
maf: 0.05                           # minimal minor allele frequency
nthreads: 50                        # maximum number of CPUs
sites:
    min_avail_prop: 0.5             # minimum proportion of non-missing samples per population
    thin: 10                        # thinning factor: (thin-1) sites are ignored before including a site
simul:
    models: []                      # choice of models to run (empty = all)
    first_batch: 1                  # index of first batch (in principle: 1)
    nbatch: 100                      # number of batches for parallelization
    szbatch: 10000                  # size of each batch (replicates)
    thin: 100                       # thin factor for progress monitoring
    priors:                         # prior specifications (see priors in simul.py)
        N: [normal, 1, 3, 0.1, 10]
        T: [normal, 0.2, 0.5, 0, 1.5]
        S: [normal, 0.5, 0.75, 0, 2]
        M: [normal, 0.5, 0.5, 0, 2]
        m: [normal, 0.1, 0.2, 0, 1]
    overwrite: no                   # whether existing files should be overwritten (use non-0 with care)
    intercept: no                  # whether errors shouls be silently caught and saved in a file (applies to posterior simulations too)
models:                            # specify a color and symbol for each model (or model grouping)
    M31: [aqua, o]
    M3B: [aquamarine, ^]
    M32: [azure, v]
    M33: [beige, s]
    M34: [black, o]
    M3C: [blue, ^]
    M35: [brown, v]
    M36: [chartreuse, s]
    M37: [chocolate, o]
    M38: [coral, ^]
    M39: [crimson, v]
    M3A: [cyan, s]
    M3D: [darkblue, o]
    M40: [darkgreen, ^]
    M41: [fuchsia, v]
    M42: [gold, s]
    M43: [goldenrod, o]
    M44: [green, ^]
    M45: [grey, v]
    M46: [indigo, s]
    M47: [khaki, o]
    M48: [lightblue, ^]
    with: [magenta]
    without: [blue]
    NA: [green, o]
    BR: [blue, o]
    EU: [red, o]
priors:
    num: 10000                      # max number of draws from each parameter
    bins: 20                        # number of bins in histograms
plot:
    stop: 100000                    # stop using replicates when this number is reached
    bins: 50                        # number of bins in histogram
lda:
    models: []                      # list of models to include (by default, all)
    stop: 50000                     # stop using replicates when this number is reached
    step: 100                       # thinning factor for plot
    bins: 100                       # number of bins in histogram
    struct:
        - - [1,2]
        - - [3,4]
        - - [5,6]
                                    # a matrix with rows=rows of the picture
                                    # columns=columns of the picture
                                    # item: 2-item list giving the dimensions to use for that plot
                                    # or 0 for disabling the plot
    pad: 1                          # pad between plots
modelchoice:
    overwrite: no                   # skip if destination directory exists
    nsam:                           # number of samples to consider
        - 1000
        - 2000
        - 3000
        - 4000
        - 5000
    analyses:                       # set of analyses to perform
        first:                      # name of the analysis
            models: [               # specify list of models to process
                M31, M3B, M32, M33, M34, M3C, M35,
                M36, M37, M38, M39, M3A, M3D]
            


post:
    models: [M33, M44]              # models to process
    prior: 10000                    # number of simulated points to import for prior
    lda: 1000                       # number of points to import for LDA
    sim_n: 40                       # number of posterior simulation batches
    sim_sz: 250                     # number of simulations in each posterior batch
    sim_thin: 50                    # progress messages frequency
    sim_overwrite: no               # perform simulations even if output files are here
    bins: 20                        # number of bins in statistics histograms
