#!/bin/bash
#SBATCH --job-name=fit2
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=demita@gmail.com
#SBATCH --partition=fast
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=50
#SBATCH --mem=128G
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks-per-socket=1
#SBATCH --time=24:00:00
#SBATCH --output=fit2.log
pwd; hostname; date
module load  python/3.9
cd ~/ABC
srun python abcranger.py
date
