#!/bin/bash
#SBATCH --job-name=collefit
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=demita@gmail.com
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=50
#SBATCH --mem=64G
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks-per-socket=1
#SBATCH --time=24:00:00
#SBATCH -p workq
#SBATCH --output=colletotrichum_%j.log     # Standard output and error log
pwd; hostname; date
module load  devel/python/Python-3.11.1
cd /home/demita/work/colletotrichum
srun python abcranger.py
date
